[package]
name = "pd2lcp-iced"
version = "1.0.0"
edition = "2024"

[features]
gamemode = []

[dependencies]
color-eyre = "0.6.5"
iced = { version = "0.14.0", features = ["svg", "tokio"] }
libpd2lcp = { path = "../libpd2lcp" }
rfd = "0.17.2"
tokio = "1.53.1"

[package.metadata.appimage]
icon = "../../icon.svg"
desktop_entry = "../../pd2lcp.desktop"
