[package]
name = "libpd2lcp"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
fs-err = "3.3.1"
hex = "0.4.3"
reqwest = { version = "0.13.4" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["process"] }
